# fullnameOverride: ingress-nginx-http

controller:
  replicaCount: "2"

  # https://github.com/kubernetes/ingress-nginx/issues/7837
  allowSnippetAnnotations: false

  ingressClass: "nginx"

  containerPort:
    http: 80
    https: 443
    special: 8000

  service:
    type: NodePort

    nodePorts:
      http: 30080
      https: 30443
      tcp:
        "8200": 30200

    externalTrafficPolicy: Local

tcp:
  "8200": "ingress-nginx/ingress-nginx-defaultbackend:80"

defaultBackend:
  enabled: true